### PR TITLE
Update the README.md file to describe the repo.

### PR DESCRIPTION
**Pull request by jill880829**
try the github pull request function

### CODE REVIEW

**Review by louisc1028 — APPROVED** [review]
LGTM!

**Review by louisc1028 — APPROVED** [review]

**Comment by louisc1028** [comment]
Hmm, the PR cannot be merged. Can you add me as the collaborator of this project?

**Comment by jill880829** [comment]
> LGTM!

Hi Louis,  I'm not sure why can't I merge the branch to the master one. Maybe the possible reason is you haven't accepted my collaborator invitation?

**Review by louisc1028 — APPROVED** [review]
Try again!

**Comment by louisc1028** [comment]
Works now! :)

**Pull request merged**
